#!/bin/bash


__dirname="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Colors
blue='\x1b[94m'
bold='\x1b[1m'
reset='\x1b[0m'

function echo_info {
    echo -e "${blue}${bold}==>${reset} ${bold}$1 ${reset}"
}

function is_symlink () {
    if [ -L "$1" ]; then
        return 0
    fi
    return 1
}

function is_normal_file () {
    if [ -f "$1" ] && [ ! -L "$1" ]; then
        return 0
    fi
    return 1
}

function is_directory () {
    if [ -d "$1" ]; then
        return 0
    fi
    return 1
}

function remove_file() {
    if is_normal_file "$1"; then
        rm -f "$1"
        return 0
    fi
    if [ -f "$1" ]; then
        unlink "$1"
        return 0
    fi
    return 1
}


###############################
# Create required directories #
###############################

mkdir -p ~/bin
mkdir -p ~/.config
mkdir -p ~/.local


########
# Bash #
########


if is_normal_file ~/.bashrc ; then
    mv ~/.bashrc ~/.bashrc.old
    echo_info "Moving existing .bashrc to .bashrc.old"
fi
if is_symlink ~/.bashrc ; then
    unlink ~/.bashrc
fi

remove_file ~/.bash_aliases
remove_file ~/.config/dircolors

ln -s "$__dirname/bash/init.sh"    ~/.bashrc
ln -s "$__dirname/bash/aliases.sh" ~/.bash_aliases

ln -s "$__dirname/dircolors"       ~/.config/dircolors

##################
# Install neovim #
##################

if ! is_normal_file ~/.local/nvim.appimage; then
    echo_info "Installing neovim"

    cd ~/.local

    wget https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
    chmod +x nvim.appimage

    remove_file ~/bin/nvim
    ln -s ~/.local/nvim.appimage ~/bin/nvim

fi

if ! is_directory ~/.config/nvim; then
    echo_info "Installing neovim configuration files"

    cd ~/.config
    git clone https://github.com/romgrk/nvim
    nvim --headless +PlugInstall +qa
fi
