#!/bin/bash


__dirname="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Colors
blue='\x1b[94m'
green='\x1b[92m'
red='\x1b[91m'
bold='\x1b[1m'
reset='\x1b[0m'

function echo_info {
    echo -e "${blue}${bold}==>${reset} ${bold}$1 ${reset}"
}
function echo_success {
    echo -e "${green}${bold}==>${reset} ${bold}$1 ${reset}"
}
function echo_error {
    echo -e "${red}${bold}==>${reset} ${bold}$1 ${reset}"
}

function is_symlink () {
    if [ -L "$1" ]; then
        return 0
    fi
    return 1
}

function is_normal_file () {
    if [ -f "$1" ] && [ ! -L "$1" ]; then
        return 0
    fi
    return 1
}

function is_directory () {
    if [ -d "$1" ]; then
        return 0
    fi
    return 1
}

function remove_file() {
    if is_normal_file "$1"; then
        rm -f "$1"
        return 0
    fi
    if [ -f "$1" ]; then
        unlink "$1"
        return 0
    fi
    return 1
}


###############################
# Create required directories #
###############################

mkdir -p ~/bin
mkdir -p ~/.cache
mkdir -p ~/.config
mkdir -p ~/.local


########
# Bash #
########


if is_normal_file ~/.bashrc ; then
    mv ~/.bashrc ~/.bashrc.old
    echo_info "Moving existing .bashrc to .bashrc.old"
fi
if is_symlink ~/.bashrc ; then
    unlink ~/.bashrc
fi

remove_file ~/.bash_aliases
remove_file ~/.config/dircolors

ln -s "$__dirname/bash/init.sh"    ~/.bashrc
ln -s "$__dirname/bash/aliases.sh" ~/.bash_aliases

ln -s "$__dirname/dircolors"       ~/.config/dircolors


##################
# Install python #
##################

if [[ "$(which python)" =~ ".*not found.*" ]]; then
    echo_info "Installing python"

    if [[ "$(uname -a)" =~ .*Ubuntu.* ]]; then
        sudo apt install python python3 python-pip python3-pip
    else
        echo_error "Can't install python for: $(uname -a)"
    fi

    pip install neovim
    pip3 install neovim
fi


##################
# Install nodejs #
##################

if [[ "$(which node)" =~ ".*not found.*" ]]; then
    echo_info "Installing nodejs"

    if [[ "$(uname -a)" =~ .*Ubuntu.* ]]; then
        # Using Ubuntu
        curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
        sudo apt install -y nodejs
    else
        echo_error "Can't install nodejs for: $(uname -a)"
    fi

    npm set prefix ~/.cache/npm
    npm install -g yarn
    npm install -g neovim
fi


##################
# Install neovim #
##################

if ! is_normal_file ~/.local/nvim.appimage && ! command -v nvim &> /dev/null ; then
    echo_info "Installing neovim"

    cd ~/.local

    wget https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
    chmod +x nvim.appimage

    remove_file ~/bin/nvim
    ln -s ~/.local/nvim.appimage ~/bin/nvim

    echo_success "Installed neovim"
else
    echo_success "Neovim already installed"
fi

if ! is_directory ~/.config/nvim; then
    echo_info "Installing neovim configuration files"

    cd ~/.config
    git clone https://github.com/romgrk/nvim
    nvim --headless +PlugInstall +qa
    echo "\n"

    echo_success "Installed neovim configuration files"
else
    echo_info "Updating neovim configuration files"

    cd ~/.config/nvim
    git pull
    nvim --headless +PlugInstall +PlugUpdate +qa
    echo "\n"

    echo_success "Updated neovim configuration files"
fi
